version: '3.7'

services:

  app:
    container_name: app
    build:
      dockerfile: Dockerfile
    depends_on:
      - clickhouse-server
      - database_mariadb
      - rabbitmq

  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    env_file:
      - .env
    ports:
      - '${CLICKHOUSE_PORT}:${CLICKHOUSE_PORT}'
    ulimits:
      nofile: 262144

  database_mariadb:
    image: mariadb:latest
    container_name: database_mariadb
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - '${MARIADB_PORT}:${MARIADB_PORT}'

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - '${RABBITMQ_PORT}:${RABBITMQ_PORT}'