version: '3.7'

services:

  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    ports:
      - '8123:8123'
      - '9004:9004'
    volumes:
      - ./db:/var/lib/clickhouse
    ulimits:
      nofile: 262144

  database_mariadb:
    image: mariadb:latest
    container_name: database_mariadb
    environment:
      MARIADB_DATABASE: callmedia
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    ports:
      - '3306:3306'